name: 'open_finops_transformations'
version: '0.1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  finops_focus:
    # Vendor enablement - consumers MUST set this
    enabled_vendors: []  # Options: ['gcp', 'aws', 'azure']

    # Schema configuration - consumers can override
    schemas:
      staging: staging
      intermediate: staging
      unified: marts

    # GCP-specific configuration
    # export_type: Billing export type - 'standard' (default) or 'resource'
    #   - standard: Resource columns (resource_name, resource_global_name) set to NULL
    #   - resource: Resource columns extracted from source (requires resource-level export)
    gcp:
      export_type: standard
      labels: []
      project_labels: []
      system_labels:
        - key: compute.googleapis.com/machine_spec
          name: machine_spec
        - key: compute.googleapis.com/cores
          name: cores
        - key: compute.googleapis.com/memory
          name: memory
        - key: compute.googleapis.com/is_unused_reservation
          name: is_unused_reservation
        - key: storage.googleapis.com/object_state
          name: object_state

    # AWS-specific configuration
    aws:
      user_tags: []
      system_tags: []

    # Azure-specific configuration
    azure:
      user_tags: []
      system_tags: []

    # Unified layer configuration
    unified:
      custom_columns: []  # Consumer can define tag/label mappings across vendors

models:
  dbt_finops_focus:
    staging:
      +materialized: view
      +schema: "{{ var('finops_focus', {}).get('schemas', {}).get('staging', 'staging') }}"
      gcp:
        +enabled: "{{ 'gcp' in var('finops_focus', {}).get('enabled_vendors', []) }}"
      aws:
        +enabled: "{{ 'aws' in var('finops_focus', {}).get('enabled_vendors', []) }}"
      azure:
        +enabled: "{{ 'azure' in var('finops_focus', {}).get('enabled_vendors', []) }}"
    intermediate:
      +schema: "{{ var('finops_focus', {}).get('schemas', {}).get('intermediate', 'staging') }}"
      gcp:
        +enabled: "{{ 'gcp' in var('finops_focus', {}).get('enabled_vendors', []) }}"
      aws:
        +enabled: "{{ 'aws' in var('finops_focus', {}).get('enabled_vendors', []) }}"
      azure:
        +enabled: "{{ 'azure' in var('finops_focus', {}).get('enabled_vendors', []) }}"
    unified:
      +schema: "{{ var('finops_focus', {}).get('schemas', {}).get('unified', 'marts') }}"
