WITH source AS (
    SELECT * FROM {{ source('azure_billing', 'azure_focus_data') }}
),

renamed AS (
    SELECT
        -- FOCUS standard columns
        BilledCost AS billed_cost,
        BillingAccountId AS billing_account_id,
        BillingAccountName AS billing_account_name,
        BillingAccountType AS billing_account_type,
        BillingCurrency AS billing_currency,
        BillingPeriodEnd AS billing_period_end,
        BillingPeriodStart AS billing_period_start,
        ChargeCategory AS charge_category,
        ChargeClass AS charge_class,
        ChargeDescription AS charge_description,
        ChargeFrequency AS charge_frequency,
        ChargePeriodEnd AS charge_period_end,
        ChargePeriodStart AS charge_period_start,
        CommitmentDiscountCategory AS commitment_discount_category,
        CommitmentDiscountId AS commitment_discount_id,
        CommitmentDiscountName AS commitment_discount_name,
        CommitmentDiscountStatus AS commitment_discount_status,
        CommitmentDiscountType AS commitment_discount_type,
        ConsumedQuantity AS consumed_quantity,
        ConsumedUnit AS consumed_unit,
        ContractedCost AS contracted_cost,
        ContractedUnitPrice AS contracted_unit_price,
        EffectiveCost AS effective_cost,
        InvoiceIssuerName AS invoice_issuer_name,
        ListCost AS list_cost,
        ListUnitPrice AS list_unit_price,
        PricingCategory AS pricing_category,
        PricingQuantity AS pricing_quantity,
        PricingUnit AS pricing_unit,
        ProviderName AS provider_name,
        PublisherName AS publisher_name,
        RegionId AS region_id,
        RegionName AS region_name,
        ResourceId AS resource_id,
        ResourceName AS resource_name,
        ResourceType AS resource_type,
        ServiceCategory AS service_category,
        ServiceName AS service_name,
        SkuId AS sku_id,
        SkuPriceId AS sku_price_id,
        SubAccountId AS sub_account_id,
        SubAccountName AS sub_account_name,
        SubAccountType AS sub_account_type,
        Tags AS tags,

        -- Azure-specific x_ columns
        x_AccountId AS x_account_id,
        x_AccountName AS x_account_name,
        x_AccountOwnerId AS x_account_owner_id,
        x_BilledCostInUsd AS x_billed_cost_in_usd,
        x_BilledUnitPrice AS x_billed_unit_price,
        x_BillingAccountId AS x_billing_account_id,
        x_BillingAccountName AS x_billing_account_name,
        x_BillingExchangeRate AS x_billing_exchange_rate,
        x_BillingExchangeRateDate AS x_billing_exchange_rate_date,
        x_BillingProfileId AS x_billing_profile_id,
        x_BillingProfileName AS x_billing_profile_name,
        x_ContractedCostInUsd AS x_contracted_cost_in_usd,
        x_CostAllocationRuleName AS x_cost_allocation_rule_name,
        x_CostCenter AS x_cost_center,
        x_CustomerId AS x_customer_id,
        x_CustomerName AS x_customer_name,
        x_EffectiveCostInUsd AS x_effective_cost_in_usd,
        x_EffectiveUnitPrice AS x_effective_unit_price,
        x_InvoiceId AS x_invoice_id,
        x_InvoiceIssuerId AS x_invoice_issuer_id,
        x_InvoiceSectionId AS x_invoice_section_id,
        x_InvoiceSectionName AS x_invoice_section_name,
        x_ListCostInUsd AS x_list_cost_in_usd,
        x_PartnerCreditApplied AS x_partner_credit_applied,
        x_PartnerCreditRate AS x_partner_credit_rate,
        x_PricingBlockSize AS x_pricing_block_size,
        x_PricingCurrency AS x_pricing_currency,
        x_PricingSubcategory AS x_pricing_subcategory,
        x_PricingUnitDescription AS x_pricing_unit_description,
        x_PublisherCategory AS x_publisher_category,
        x_PublisherId AS x_publisher_id,
        x_ResellerId AS x_reseller_id,
        x_ResellerName AS x_reseller_name,
        x_ResourceGroupName AS x_resource_group_name,
        x_ResourceType AS x_resource_type,
        x_ServicePeriodEnd AS x_service_period_end,
        x_ServicePeriodStart AS x_service_period_start,
        x_SkuDescription AS x_sku_description,
        x_SkuDetails AS x_sku_details,
        x_SkuIsCreditEligible AS x_sku_is_credit_eligible,
        x_SkuMeterCategory AS x_sku_meter_category,
        x_SkuMeterId AS x_sku_meter_id,
        x_SkuMeterName AS x_sku_meter_name,
        x_SkuMeterSubcategory AS x_sku_meter_subcategory,
        x_SkuOfferId AS x_sku_offer_id,
        x_SkuOrderId AS x_sku_order_id,
        x_SkuOrderName AS x_sku_order_name,
        x_SkuPartNumber AS x_sku_part_number,
        x_SkuRegion AS x_sku_region,
        x_SkuServiceFamily AS x_sku_service_family,
        x_SkuTerm AS x_sku_term,
        x_SkuTier AS x_sku_tier

    FROM source
)

SELECT * FROM renamed
